EXTRA_INCLUDEPATH += /Users/tkashem/Desktop/github_repos/machine-learning/env/include /Users/tkashem/Desktop/github_repos/machine-learning/env/include/mysql /Users/tkashem/Desktop/github_repos/machine-learning/env/include/gstreamer-1.0 /Users/tkashem/Desktop/github_repos/machine-learning/env/include/glib-2.0 /Users/tkashem/Desktop/github_repos/machine-learning/env/lib/glib-2.0/include
EXTRA_LIBDIR += /Users/tkashem/Desktop/github_repos/machine-learning/env/lib
QT_CPU_FEATURES.x86_64 = cx16 mmx sse sse2 sse3 ssse3 sse4.1
QT.global_private.enabled_features = sse2 alloca_h alloca avx2 dbus dlopen gui network reduce_exports relocatable sql system-zlib testlib widgets xml zstd
QT.global_private.disabled_features = alloca_malloc_h android-style-assets private_tests dbus-linked gc_binaries intelcet libudev posix_fallocate reduce_relocations release_tools stack-protector-strong
QMAKE_LIBS_LIBDL = 
QT_COORD_TYPE = double
QMAKE_LIBS_ZLIB = -lz
QMAKE_LIBS_ZSTD = -lzstd
CONFIG += sse2 aesni sse3 ssse3 sse4_1 sse4_2 avx avx2 avx512f avx512bw avx512cd avx512dq avx512er avx512ifma avx512pf avx512vbmi avx512vl compile_examples f16c largefile optimize_size precompile_header rdrnd rdseed shani x86SimdAlways
QT_BUILD_PARTS += libs tools
QT_HOST_CFLAGS_DBUS += 
EXTRA_RPATHS += /Users/tkashem/Desktop/github_repos/machine-learning/env/lib
